const aleacionesData = [
    { 
      id: 1, 
      name: 'Ti-6Al-4V', 
      image:'/TiAlV.png', 
      width: 170, 
      height: 100,
      description:'Esta aleación de titanio, compuesta principalmente de titanio, aluminio y vanadio, es ampliamente utilizada en aplicaciones médicas debido a su combinación de alta resistencia y biocompatibilidad. Su capacidad de fusionarse con el hueso y resistir la corrosión lo convierte en un material esencial para implantes ortopédicos, como prótesis de cadera y placas de fijación ósea. La importancia de esta aleación radica en su capacidad para restaurar la movilidad y la calidad de vida de pacientes que necesitan reemplazar articulaciones dañadas.',
      biomaterialesId:[1,2],
      dispositivosId:[1],
    },
    { 
      id: 2, 
      name: 'NitiNol', 
      image:'/Nitinol.jpg', 
      width: 300, 
      height: 300,
      description:'El Nitinol es una aleación única de níquel y titanio con la asombrosa propiedad de recuperar su forma original después de ser deformada. Esto lo convierte en un material esencial en dispositivos médicos como stents vasculares. Los stents fabricados con Nitinol se expanden y se mantienen en su lugar para mantener las arterias abiertas, evitando la obstrucción y mejorando el flujo sanguíneo. Esta propiedad es crucial para prevenir o tratar afecciones como la enfermedad arterial coronaria. La importancia del Nitinol en medicina radica en su capacidad para mejorar la salud cardiovascular y salvar vidas.',
      biomaterialesId:[1,6],
      dispositivosId:[2],
    },
    { 
      id: 3, 
      name: 'Co-Cr-Mo', 
      image:'/CoCrMo.jpg', 
      width: 200, 
      height: 300 ,
      description:'Esta aleación, compuesta de cobalto, cromo y molibdeno, es conocida por su resistencia y durabilidad. Se utiliza en implantes ortopédicos, como componentes de prótesis de cadera y rodilla. Su capacidad para soportar altas cargas y desgaste lo hace esencial en la restauración de la movilidad en pacientes con articulaciones dañadas o desgastadas. La importancia del Co-Cr-Mo en medicina radica en su capacidad para aliviar el dolor y mejorar la calidad de vida de los pacientes que requieren reemplazos articulares.      ',
      biomaterialesId:[7,8,9],
      dispositivosId:[3],
    },
    { 
      id: 4, 
      name: 'Ni-Cr', 
      image:'/nicro.png', 
      width: 150, 
      height: 200 ,
      description:'Las aleaciones de níquel-cromo, resistentes a la corrosión y biocompatibles, se utilizan en aplicaciones dentales, como prótesis dentales y coronas. Estos dispositivos restauran la función masticatoria y la estética dental en pacientes con dientes ausentes o dañados. La importancia del Ni-Cr en medicina radica en su capacidad para mejorar la salud bucal, la digestión y la autoestima de los pacientes.      ',
      biomaterialesId:[6,8],
      dispositivosId:[4],
    },
    { 
      id: 5, 
      name: 'Co-Cr' , 
      image:'/CoCr.jpg', 
      width: 210, 
      height: 300,
      description:'El cobalto-cromo se emplea en prótesis dentales y ortopédicas debido a su resistencia y biocompatibilidad. En la odontología, permite la restauración de dientes perdidos o dañados, mientras que en la ortopedia, proporciona soluciones de reemplazo articular duraderas. La importancia del Co-Cr en medicina radica en su capacidad para restaurar la función y la estética en pacientes con necesidades dentales y ortopédicas.     ',
      biomaterialesId:[7,8],
      dispositivosId:[5],
    },
    { 
      id: 6, 
      name: 'Mo-Ti', 
      image:'/MoTi.png', 
      width: 170, 
      height: 300 ,
      description:'Esta aleación se utiliza en aplicaciones médicas, como componentes de marcapasos y otros dispositivos implantables, debido a su resistencia y biocompatibilidad. Los marcapasos son dispositivos cruciales para regular el ritmo cardíaco en pacientes con trastornos del ritmo cardíaco, y el Mo-Ti contribuye a la confiabilidad y la eficacia de estos dispositivos. Su importancia en medicina radica en su capacidad para mejorar la salud cardiovascular y la calidad de vida de los pacientes.',
      biomaterialesId:[1,9],
      dispositivosId:[6],
    },
  ];

  export default aleacionesData;