const aleacionesData = [
    { 
      id: 1, 
      name: 'Ti-6Al-4V', 
      image:'/TiAlV.png', 
      width: 170, 
      height: 100,
      description:'',
      biomaterialesId:[1,2],
      dispositivosId:[1],
    },
    { 
      id: 2, 
      name: 'NitiNol', 
      image:'/Nitinol.jpg', 
      width: 300, 
      height: 300,
      description:'',
      biomaterialesId:[1,6],
      dispositivosId:[2],
    },
    { 
      id: 3, 
      name: 'Co-Cr-Mo', 
      image:'/CoCrMo.jpg', 
      width: 200, 
      height: 300 ,
      description:'',
      biomaterialesId:[7,8,9],
      dispositivosId:[3],
    },
    { 
      id: 4, 
      name: 'Ni-Cr', 
      image:'/nicro.png', 
      width: 150, 
      height: 200 ,
      description:'',
      biomaterialesId:[6,8],
      dispositivosId:[4],
    },
    { 
      id: 5, 
      name: 'Co-Cr' , 
      image:'/CoCr.jpg', 
      width: 210, 
      height: 300,
      description:'',
      biomaterialesId:[7,8],
      dispositivosId:[5],
    },
    { 
      id: 6, 
      name: 'Mo-Ti', 
      image:'/MoTi.png', 
      width: 170, 
      height: 300 ,
      description:'',
      biomaterialesId:[1,9],
      dispositivosId:[6],
    },
  ];

  export default aleacionesData;