const biomaterialesData = [
  { 
    id: 1, 
    name: 'Titanio', 
    image:'/Titanio.webp', 
    width: 250, 
    height: 300,
    description:'El titanio es un material biomédico altamente valorado debido a su excepcional biocompatibilidad, resistencia a la corrosión, alta resistencia y baja densidad, lo que lo hace idóneo para aplicaciones médicas como implantes ortopédicos y dispositivos dentales. Su capacidad de osteointegración, durabilidad a largo plazo y facilidad de mecanizado hacen que sea esencial en la fabricación de dispositivos médicos que requieren adaptabilidad y longevidad, permitiendo mejorar la calidad de vida de pacientes que necesitan prótesis y tratamientos médicos implantables.',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 2, 
    name: 'Vanadio', 
    image:'/vanadio.png', 
    width: 240, 
    height: 300,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 3, 
    name: 'Hidrogel', 
    image:'/Gelatine-3.jpg', 
    width: 220, 
    height: 300 ,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 4, 
    name: 'Polietileno de alta densidad', 
    image:'/pead.jpg', 
    width: 260, 
    height: 200 ,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 5, 
    name: 'Polietileno de ultra alto peso molecular' , 
    image:'/UHMWPE.png', 
    width: 210, 
    height: 300,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 6, 
    name: 'Niquel', 
    image:'/niquel.png', 
    width: 170, 
    height: 300 ,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 7, 
    name: 'Cobalto', 
    image:'/cobalto3.png', 
    width: 200, 
    height: 300 ,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 8, 
    name: 'Cromo', 
    image:'/Cromo.png', 
    width: 250, 
    height: 300 ,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
  { 
    id: 9, 
    name: 'Molibdeno', 
    image:'/molibdeno - copia.png', 
    width: 250, 
    height: 200 ,
    description:'El titanio..',
    aleacionesId:[1,2,6],
    dispositivosId:[1,2,6],
  },
];

export default biomaterialesData;