const proveedoresData = [
    { 
      id: 1, 
      name: 'GPC Medical Colombia SAS',
      Image:'/Gpc-Medical-logo.jpg',
      width: 150, 
      height: 100,
      telefono: '+57 3122620329',
      Email: 'edgar@gpcmedical.com.co',
      Url: 'https://www.gpcmedical.com.co',
      description:'Proveedor de productos ortopedicos de alta calidad.',
      dispositivosId:[1],
      paisesId:[1],
    },
    { 
      id: 2, 
      name: 'Biotronik Spain SA',  
      Image:'/logobiotronik.png',
      width: 150, 
      height: 300,
      telefono: '+34 917994670',
      Email: 'carla.tudela@biotronik.com',
      Url: 'https://www.biotronik.com/es-es',
      description:'Empresa privada de ámbito mundial de dispositivos médicos que dispone de productos y servicios que salvan y mejoran la vida de pacientes que sufren enfermedades cardiovasculares y endovasculares.',
      dispositivosId:[2],
      paisesId:[2],
    },
    { 
      id: 3, 
      name: 'Changzhou WastonOrtho Medical Appliance Co., Ltd.', 
      Image:'/wastonorthoLogo.png',
      width: 160, 
      height: 300,
      telefono: '+86-519-86522226',
      Email: 'info@wastonmed.com',
      Url: 'http://www.wastonortho.com/',
      description:'Empresa desarrolladora y productora de productos medicos de alta calidad que son clínicamente relevantes y fáciles de usar',
      dispositivosId:[3],
      paisesId:[3],
    },
    { 
      id: 4, 
      name: 'BioDentales de Colombia Ltda.',  
      Image:'/Biodentales49-a.png',
      width: 220,
      height: 200,
      telefono: '+57 316 3560022',
      Email: '-',
      Url: 'https://biodentales.com/',
      description:'Empresa proveedora de Materiales, Instrumentos, Equipos y Sistemas Cad-Cam de la más Alta Tecnología y Calidad para Rehabilitación Oral y Laboratorio Dental.',
      dispositivosId:[4],
      paisesId:[1],
      },
    { 
      id: 5, 
      name: 'MEDICO SRL' , 
      Image:'/logo_medico2016-1.png',
      width: 190, 
      height: 300,
      telefono: '+39 049 8976755',
      Email: 'info@medicoweb.com',
      Url: 'http://www.medicoweb.com',
      description:'Empresa privada e independiente que opera en el campo de la cardioestimulación con el objetivo de garantizar a médicos y pacientes un estándar tecnológico de alto nivel.',
      dispositivosId:[5],
      paisesId:[4],
    },
    { 
      id: 6, 
      name: 'C-Tech Implant', 
      Image:'/CtechLogo.png',
      width: 240, 
      height: 300,
      telefono: '+39 051 66 61 817',
      Email: 'info@c-tech-implant.com',
      Url: 'https://www.c-tech-implant.com/es/',
      description:'Empresa dedicada a diseñar, producir y suministrar implantes dentales a mas de 25 paises.',
      dispositivosId:[6],
      paisesId:[4],
    },
    { 
      id: 7, 
      name: 'MBA SURGICAL EMPOWERMENT', 
      Image:'/mbasurgicalempowerment_logo.jpeg',
      width: 260, 
      height: 300,
      telefono: '+34 985 195 505',
      Email: 'info@mba.eu',
      Url: 'https://www.mba.eu/es/',
      description:'Multinacional española, líder en el sector de la distribución de tecnología médico-quirúrgica con presencia en España, Portugal e Italia.',
      dispositivosId:[1],
      paisesId:[2],
    },
    { 
      id: 8, 
      name: 'Thommen Medical', 
      Image:'/logoTM.svg',
      width: 150, 
      height: 300,
      telefono: '+41 61 965 90 20',
      Email: 'info@thommenmedical.com',
      Url: 'https://www.thommenmedical.com/en',
      description:'Empresa suiza fabricante de implantes dentales, la cual ofrece una amplia gama de implantes óseos y brinda soluciones implantológicas a pacientes con distintos requerimientos.',
      dispositivosId:[6],
      paisesId:[5],
    },
  ];

  export default proveedoresData;